import { Link, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useClientPeriod } from '../context/ClientPeriodContext';
import { getStatements } from '../api/reports';
import { Figure } from '../components/Figure';
import { ErrorState } from '../components/ErrorState';
import { LoadingState } from '../components/LoadingState';
import { PrintButton, PrintFooter } from '../components/PrintFooter';
import { formatDate, formatMoney } from '../utils/format';

// Print output must contain no em dashes at all — every Figure on this page passes "-" as
// its zero placeholder instead of the app-wide default "—".
const ZERO = '-';

function StatementRows({ lines }: { lines: { accountId: string; name: string; amount: string }[] }) {
  return (
    <>
      {lines.map((line) => (
        <tr key={line.accountId}>
          <td style={{ padding: '4px 8px' }}>{line.name}</td>
          <td style={{ padding: '4px 8px', textAlign: 'right' }} className="figure">
            <Figure value={line.amount} zeroDisplay={ZERO} showZero />
          </td>
        </tr>
      ))}
    </>
  );
}

// Generated by the Trial Balance page's "Prepare financial statements" button. Both
// statements come from GET /reports/statements, which is built from the same
// movementByTypeInRange/balancesByType queries the Ledger and Trial Balance pages use —
// there is nowhere for these three to independently drift apart.
export function FinancialStatementsPage() {
  const { clientId } = useClientPeriod();
  const [searchParams] = useSearchParams();
  const from = searchParams.get('from') ?? '';
  const to = searchParams.get('to') ?? '';

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['statements', clientId, from, to],
    queryFn: () => getStatements(clientId!, from, to),
    enabled: !!clientId && !!from && !!to,
  });

  return (
    <div className="statements-print">
      <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 'var(--space-3)' }}>
        <Link to="/trial-balance">← Back to trial balance</Link>
        <PrintButton />
      </div>

      <h2>Financial statements</h2>

      {isError && <ErrorState message={error instanceof Error ? error.message : 'Failed to generate statements'} />}
      {isLoading && <LoadingState label="Preparing statements…" />}

      {data && (
        <>
          <div style={{ maxWidth: 640, marginBottom: 'var(--space-6)' }}>
            <h3>Income statement</h3>
            <p style={{ color: 'var(--ink-muted)', marginTop: 0 }}>
              For the period {formatDate(data.range.fromDate)} to {formatDate(data.range.toDate)}
            </p>
            <p style={{ fontSize: 12, color: 'var(--ink-muted)' }}>{data.incomeStatement.basisOfPreparation}</p>

            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <tbody>
                <StatementRows lines={data.incomeStatement.income} />
                <tr style={{ borderTop: '1px solid var(--ink)' }}>
                  <td style={{ padding: '4px 8px', fontWeight: 600 }}>Total revenue</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right', fontWeight: 600 }}>
                    <Figure value={data.incomeStatement.totalIncome} zeroDisplay={ZERO} showZero />
                  </td>
                </tr>
              </tbody>
            </table>

            {data.incomeStatement.hasCostOfSales && (
              <>
                <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 'var(--space-3)' }}>
                  <tbody>
                    <StatementRows lines={data.incomeStatement.costOfSales} />
                    <tr style={{ borderTop: '1px solid var(--ink)' }}>
                      <td style={{ padding: '4px 8px', fontWeight: 600 }}>Total cost of sales</td>
                      <td style={{ padding: '4px 8px', textAlign: 'right', fontWeight: 600 }}>
                        <Figure value={data.incomeStatement.totalCostOfSales} zeroDisplay={ZERO} showZero />
                      </td>
                    </tr>
                    <tr style={{ borderTop: '1px solid var(--ink)', borderBottom: '3px double var(--ink)' }}>
                      <td style={{ padding: '6px 8px', fontWeight: 700 }}>Gross profit</td>
                      <td style={{ padding: '6px 8px', textAlign: 'right', fontWeight: 700 }}>
                        <Figure value={data.incomeStatement.grossProfit} zeroDisplay={ZERO} showZero />
                      </td>
                    </tr>
                  </tbody>
                </table>
              </>
            )}

            <h4 style={{ marginTop: 'var(--space-4)' }}>Operating expenses</h4>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <tbody>
                <StatementRows lines={data.incomeStatement.operatingExpenses} />
                <tr style={{ borderTop: '1px solid var(--ink)' }}>
                  <td style={{ padding: '4px 8px', fontWeight: 600 }}>Total operating expenses</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right', fontWeight: 600 }}>
                    <Figure value={data.incomeStatement.totalOperatingExpenses} zeroDisplay={ZERO} showZero />
                  </td>
                </tr>
              </tbody>
            </table>

            <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 'var(--space-4)' }}>
              <tbody>
                <tr style={{ borderTop: '1px solid var(--ink)', borderBottom: '3px double var(--ink)' }}>
                  <td style={{ padding: '6px 8px', fontWeight: 700 }}>
                    {data.incomeStatement.profitForPeriod.startsWith('-') ? 'Net loss for the period' : 'Net profit for the period'}
                  </td>
                  <td style={{ padding: '6px 8px', textAlign: 'right', fontWeight: 700 }}>
                    <Figure value={data.incomeStatement.profitForPeriod} zeroDisplay={ZERO} showZero />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div style={{ maxWidth: 640 }}>
            <h3>Statement of financial position</h3>
            <p style={{ color: 'var(--ink-muted)', marginTop: 0 }}>As at {formatDate(data.balanceSheet.asAt)}</p>
            <p style={{ fontSize: 12, color: 'var(--ink-muted)' }}>{data.balanceSheet.basisOfPreparation}</p>

            {!data.balanceSheet.balances && (
              <div style={{ marginBottom: 'var(--space-3)' }}>
                <ErrorState
                  message={`This balance sheet does not balance: total assets ${formatMoney(data.balanceSheet.totalAssets)} vs total liabilities and equity ${formatMoney(data.balanceSheet.totalLiabilitiesAndEquity)} (difference ${formatMoney(data.balanceSheet.difference)}). The figures below are shown as posted — check the trial balance to find the mistake.`}
                />
              </div>
            )}

            <h4>Assets</h4>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <tbody>
                <StatementRows lines={data.balanceSheet.assets} />
                <tr style={{ borderTop: '1px solid var(--ink)' }}>
                  <td style={{ padding: '4px 8px', fontWeight: 600 }}>Total assets</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right', fontWeight: 600 }}>
                    <Figure value={data.balanceSheet.totalAssets} zeroDisplay={ZERO} showZero />
                  </td>
                </tr>
              </tbody>
            </table>

            <h4 style={{ marginTop: 'var(--space-4)' }}>Liabilities</h4>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <tbody>
                <StatementRows lines={data.balanceSheet.liabilities} />
                <tr style={{ borderTop: '1px solid var(--ink)' }}>
                  <td style={{ padding: '4px 8px', fontWeight: 600 }}>Total liabilities</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right', fontWeight: 600 }}>
                    <Figure value={data.balanceSheet.totalLiabilities} zeroDisplay={ZERO} showZero />
                  </td>
                </tr>
              </tbody>
            </table>

            <h4 style={{ marginTop: 'var(--space-4)' }}>Equity</h4>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <tbody>
                <StatementRows lines={data.balanceSheet.equity} />
                <tr style={{ borderTop: '1px solid var(--ink)', borderBottom: '3px double var(--ink)' }}>
                  <td style={{ padding: '6px 8px', fontWeight: 700 }}>Total liabilities and equity</td>
                  <td style={{ padding: '6px 8px', textAlign: 'right', fontWeight: 700 }}>
                    <Figure value={data.balanceSheet.totalLiabilitiesAndEquity} zeroDisplay={ZERO} showZero />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </>
      )}
      <PrintFooter />
    </div>
  );
}
